M48
; DRILL file {KiCad 7.0.11} date Friday, November 07, 2025 at 02:34:00 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-07T14:34:00+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X109.22Y-45.72
X109.22Y-106.68
X158.75Y-45.72
X158.75Y-106.68
M30
